### ISSUE TITLE
Consider taking a dependency on AspNet.ScriptManager.jQuery & AspNet.ScriptManager.jQuery.UI.Combined NuGet packages

### ISSUE THREAD

**Issue by DamianEdwards** [shellscape/Brew#1]
These packages are installed by default into new Web Forms applications as of Visual Studio 2012 and they handle the registration of jQuery and jQuery UI with the ScriptManager. Any other package requiring jQuery and/or jQuery UI in Web Forms would be best served by simply depending on these packages rather than re-registering the scripts itself.

**Comment by shellscape** [comment]
Curious. I'd be open to it, but I have a few questions:

Was that the motivation for creating the AspNet.ScriptManager.jQuery package vs the pre-existing jQuery package on nuget? 
How does the ScriptManager package handle other packages requiring the plain jQuery package, or is the recommendation there to abandon the plain jQuery package?
Has there been any negative feedback about littering the bin directory with more dlls?
Where is the source for those packages? Did some quick googling, couldn't track it down.

**Comment by shellscape** [comment]
Well I've looked and I've looked and I can't find a single negative thing said about packages that use those two ScriptManager packages. So I suppose I'll be adding it for the next version. Looking at doing a small maintenance release later on this week.
