### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by ghost** [shellscape/Brew#6]
Hi, you recommended me (http://stackoverflow.com/questions/15772782/juiceui-not-working-with-scriptmanager-ajaxframeworkmode-disabled/) to try Brew in an existing project. Well, I tried.

Object reference not set to an instance of an object.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error: 

[No relevant source lines]

Source File: c:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\3335c505\5d81377e\App_Web_ohwysq4j.1.cs    Line: 0 

Stack Trace: 

[NullReferenceException: Object reference not set to an instance of an object.]
   Brew.Webforms.Widget.Render(HtmlTextWriter writer) +1234
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +57
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter) +100
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer) +25
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +128
   System.Web.UI.Control.RenderChildren(HtmlTextWriter writer) +8
   System.Web.UI.Control.Render(HtmlTextWriter writer) +10
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +57
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter) +100
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer) +25
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +128
   System.Web.UI.Control.RenderChildren(HtmlTextWriter writer) +8
   System.Web.UI.WebControls.LoginView.Render(HtmlTextWriter writer) +30
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +57
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter) +100
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer) +25
   ASP.pages_site_master.__Render__control10(HtmlTextWriter __w, Control parameterContainer) in c:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\3335c505\5d81377e\App_Web_ohwysq4j.1.cs:0
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +268
   System.Web.UI.HtmlControls.HtmlForm.RenderChildren(HtmlTextWriter writer) +216
   System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer) +32
   System.Web.UI.HtmlControls.HtmlForm.Render(HtmlTextWriter output) +53
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +57
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter) +100
   System.Web.UI.HtmlControls.HtmlForm.RenderControl(HtmlTextWriter writer) +40
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +128
   System.Web.UI.Control.RenderChildren(HtmlTextWriter writer) +8
   System.Web.UI.Control.Render(HtmlTextWriter writer) +10
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +57
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter) +100
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer) +25
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +128
   System.Web.UI.Control.RenderChildren(HtmlTextWriter writer) +8
   System.Web.UI.Page.Render(HtmlTextWriter writer) +29
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +57
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter) +100
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer) +25
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +1386

Any idea? I tried create a new project and it worked as expected, but I can't get it work in my existing project.

**Comment by shellscape** [comment]
Thanks for giving it a try. I'll look into this error for you.

**Comment by ghost** [comment]
Thank you. I can provide you the complete project since it is my thesis and is aimed to be released as an open source.

**Comment by shellscape** [comment]
I tested the problem you highlighted on stackoverflow using the brew webforms website. This is how my scriptmanager tag looks:

``` xml
<asp:scriptmanager runat="server" ajaxframeworkmode="Disabled"/>
```

Everything worked as expected. If you upload your project to a filesharing site or github repo, I'll take a look at it.

**Comment by ghost** [comment]
Ok, I managed to find out where the problem roots from.

`<asp:LoginView runat="server">
                <AnonymousTemplate>
                    <button id="butan" runat="server">A button element</button>
                    <brew:Button ID="brewbutton" runat="server" For="butan" Label="new label" />
                </AnonymousTemplate>
            </asp:LoginView>`

Could you please look into this? It is a serious flaw.

**Comment by shellscape** [comment]
This has to do with using brew within templates. I posted a fix for that on
issue #5. The fix will be in the next release of Brew as well.
