### ISSUE TITLE
Strong name the Brew assemblies

### ISSUE THREAD

**Issue by nekno** [shellscape/Brew#7]
My projects taking a dependency on Brew must be strong named, and therefore the Brew assemblies must be strong named in order to reference them.

Would it be possible to strong name the assemblies for the next NuGet update?

**Comment by shellscape** [comment]
Brew is already compiled with a strong name. Is it the Brew.Webforms.dll assembly you're referring to?

**Comment by shellscape** [comment]
Please reply to the last comment. Will close for inactivity otherwise.

**Comment by nekno** [comment]
Yes --- all assemblies must be strong-named. I don't have the project in front of me, so if you're certain the NuGet distribution includes a strong-named Brew.dll, then it must be Brew.Webforms.dll that Visual Studio was complaining about.

**Comment by shellscape** [comment]
I'll post an update to nuget soon.
