### ISSUE TITLE
Support IE 8?

### ISSUE THREAD

**Issue by Nexus-42** [shellscape/Brew#9]
Brew is Compatible to IE8 what is really nasty -> Most of our Customers using Windows XP where the Browser is IE8

**Comment by shellscape** [comment]
Sorry it took me so long to reply to this. Didn't get the notification that there was a new issue.

Brew uses jQuery UI, so the short answer is "Yes." If jQuery UI updates and is no longer compatible with IE8 then the answer will change to "No." 

Hope that helps.
